Update changedfiiles.yml

diff --git a/.github/workflows/changedfiiles.yml b/.github/workflows/changedfiiles.yml
--- a/.github/workflows/changedfiiles.yml
+++ b/.github/workflows/changedfiiles.yml
@@ -17,6 +17,9 @@ jobs:
   # ----------------------------------------------------------------------------------------------
   changed_files:
     runs-on: ubuntu-latest  # windows-latest || macos-latest
+    permissions:
+      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
+      contents: write
     name: Test changed-files
     steps:
       - uses: actions/checkout@v4
@@ -39,3 +42,37 @@ jobs:
           for file in ${ALL_CHANGED_FILES}; do
             echo "$file was changed"
           done
+          
+          git config --global user.name "weblate-po4a"
+          git config --global user.email "weblate-po4a@example.com"
+          ERROR=0
+          for po_file in ${ALL_CHANGED_FILES}; do
+            # Determine the corresponding config file
+            config_file=$(echo "$po_file" | sed -E 's|_i18n/.*/resources/(.*)/weblate/.*|\1|').config
+            config_file_path="po/$config_file"
+            
+            if [ -f "$config_file_path" ]; then
+              echo "-> Running po4a on ${config_file_path}"
+              cd po
+              if po4a "${config_file_path}"; then
+                echo "po4a ran successfully on ${config_file_path}"
+                cd ..
+                git add .
+                COMMIT_MESSAGE="po4a: ${config_file_path} updates"
+                git commit -m "${COMMIT_MESSAGE}"
+              else
+                echo "ERROR: something went wrong, po4a didn't run successfully on ${config_file_path}"
+                cd ..
+                ERROR=1
+              fi
+            else
+              echo "ERROR: Config file ${config_file_path} not found, exiting."
+              ERROR=1
+            fi
+          done
+          exit $ERROR
+      - name: Push changes
+        uses: ad-m/github-push-action@master
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          branch: ${{ github.ref }}
