Update po4a.yml

diff --git a/.github/workflows/po4a.yml b/.github/workflows/po4a.yml
--- a/.github/workflows/po4a.yml
+++ b/.github/workflows/po4a.yml
@@ -49,50 +49,58 @@ jobs:
       run: |
         cd po4a
         sudo ./Build install
-
-    - name: Run po4a on corresponding config files and commit updates
+  
+    - name: Get all po, pot changes files
+      id: changed-po-files
+      uses: tj-actions/changed-files@v44
+      with:
+        files_yaml: |
+          po:
+            - '*.po'
+            - '*.pot'
+  
+    - name: Run step if po file(s) change
+      # NOTE: Ensure all outputs are prefixed by the same key used above e.g. `test_(...)` | `doc_(...)` | `src_(...)` when trying to access the `any_changed` output.
+      if: steps.changed-po-files.outputs.po_any_changed == 'true'  
+      env:
+        PO_CHANGED_FILES: ${{ steps.changed-files-yaml.outputs.po_all_changed_files }}
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
-        PREVIOUS_COMMIT=${{github.event.before}}
-        LATEST_COMMIT=${{github.sha}}
-        git diff-tree --no-commit-id --name-only -r $PREVIOUS_COMMIT..$LATEST_COMMIT
-        echo $LATEST_COMMIT
-        CHANGED_PO_FILES=$(git diff-tree --no-commit-id --name-only -r $PREVIOUS_COMMIT..$LATEST_COMMIT | grep -E '\.po$|\.pot$' || true)
-        if [ -z "$CHANGED_FILES" ]; then
-          echo "No .po or .pot files changed."
-        else
-          git config --global user.name "weblate-po4a"
-          git config --global user.email "weblate-po4a@example.com"
-          ERROR=0
-          for po_file in $CHANGED_FILES; do
-            # Determine the corresponding config file
-            config_file=$(echo "$po_file" | sed -E 's|_i18n/.*/resources/(.*)/weblate/.*|\1|').config
-            config_file_path="po/$config_file"
-            
-            if [ -f "$config_file_path" ]; then
-              echo "-> Running po4a on ${config_file_path}"
-              cd po
-              if po4a "${config_file_path}"; then
-                echo "po4a ran successfully on ${config_file_path}"
-                cd ..
-                git add .
-                COMMIT_MESSAGE="po4a: ${config_file_path} updates"
-                git commit -m "${COMMIT_MESSAGE}"
-                git push origin HEAD
-              else
-                echo "ERROR: something went wrong, po4a didn't run successfully on ${config_file_path}"
-                cd ..
-                ERROR=1
-              fi
+        echo "One or more po/ file(s) has changed."
+        echo "List all the files that have changed: $PO_ALL_CHANGED_FILES"
+        git config --global user.name "weblate-po4a"
+        git config --global user.email "weblate-po4a@example.com"
+        ERROR=0
+        for file in ${PO_CHANGED_FILES}; do
+          echo "$file was changed"
+        done
+        for po_file in $CHANGED_FILES; do
+          # Determine the corresponding config file
+          config_file=$(echo "$po_file" | sed -E 's|_i18n/.*/resources/(.*)/weblate/.*|\1|').config
+          config_file_path="po/$config_file"
+          
+          if [ -f "$config_file_path" ]; then
+            echo "-> Running po4a on ${config_file_path}"
+            cd po
+            if po4a "${config_file_path}"; then
+              echo "po4a ran successfully on ${config_file_path}"
+              cd ..
+              git add .
+              COMMIT_MESSAGE="po4a: ${config_file_path} updates"
+              git commit -m "${COMMIT_MESSAGE}"
+              git push origin HEAD
             else
-              echo "ERROR: Config file ${config_file_path} not found, exiting."
+              echo "ERROR: something went wrong, po4a didn't run successfully on ${config_file_path}"
+              cd ..
               ERROR=1
             fi
-          done
-          exit $ERROR
-        fi
-      shell: bash
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          else
+            echo "ERROR: Config file ${config_file_path} not found, exiting."
+            ERROR=1
+          fi
+        done
+        exit $ERROR
+        
     - name: Get current branch name
       id: branch-name
       run: echo "::set-output name=branch::$(git rev-parse --abbrev-ref HEAD)"  
